# Chile

In [1]:
import pandas as pd
import numpy as np
import os
import json
import gspread as gs
import warnings

from utils.clean import wrangling
from utils.top_imports import top_importadores
from utils.data_anual import annual_data
from utils.vol_origenes import analisis_origenes
from utils.target_price import price_analysis

pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.options.display.max_colwidth = None

warnings.simplefilter("ignore")

                        ### ~~~ ###
                    ###     PATH     ###
                        ### ~~~ ###

location_2013 = "./data/283525_Importaciones_2013.xlsx"
location_2014 = "./data/283525_Importaciones_2014.xlsx"
location_2015 = "./data/283525_Importaciones_2015.xlsx"
location_2016 = "./data/283525_Importaciones_2016.xlsx"
location_2017 = "./data/283525_Importaciones_2017.xlsx"
location_2018 = "./data/283525_Importaciones_2018.xlsx"
location_2019 = "./data/283525_Importaciones_2019.xlsx"
location_2020 = "./data/283525_Importaciones_2020.xlsx"
location_2021 = "./data/283525_Importaciones_2021.xlsx"
location_2022 = "./data/283525_Importaciones_2022.xlsx"
location_2023 = "./data/283525_Importaciones_2023.xlsx"

                        ### ~~~ ###
                    ###     DATA     ###
                        ### ~~~ ###

data2013 = pd.read_excel(location_2013, engine="openpyxl")
data2014 = pd.read_excel(location_2014, engine="openpyxl")
data2015 = pd.read_excel(location_2015, engine="openpyxl")
data2016 = pd.read_excel(location_2016, engine="openpyxl")
data2017 = pd.read_excel(location_2017, engine="openpyxl")
data2018 = pd.read_excel(location_2018, engine="openpyxl")
data2019 = pd.read_excel(location_2019, engine="openpyxl")
data2020 = pd.read_excel(location_2020, engine="openpyxl")
data2021 = pd.read_excel(location_2021, engine="openpyxl")
data2022 = pd.read_excel(location_2022, engine="openpyxl")
data2023 = pd.read_excel(location_2023, engine="openpyxl")

In [2]:
# MERGE
dfs = [data2013, data2014, data2015, data2016, data2017,
       data2018, data2019, data2020, data2021, data2022, data2023]

print("Este df tiene (filas, col):\n___________________")

for df in dfs:
    print(f"> {df['Fecha'][0].year}: {df.shape}\n~~~~~~~~~~~~~~~~~~~")

Este df tiene (filas, col):
___________________
> 2013: (220, 37)
~~~~~~~~~~~~~~~~~~~
> 2014: (205, 37)
~~~~~~~~~~~~~~~~~~~
> 2015: (249, 37)
~~~~~~~~~~~~~~~~~~~
> 2016: (280, 37)
~~~~~~~~~~~~~~~~~~~
> 2017: (255, 37)
~~~~~~~~~~~~~~~~~~~
> 2018: (249, 37)
~~~~~~~~~~~~~~~~~~~
> 2019: (202, 37)
~~~~~~~~~~~~~~~~~~~
> 2020: (215, 37)
~~~~~~~~~~~~~~~~~~~
> 2021: (220, 37)
~~~~~~~~~~~~~~~~~~~
> 2022: (243, 37)
~~~~~~~~~~~~~~~~~~~
> 2023: (15, 37)
~~~~~~~~~~~~~~~~~~~

In [3]:
# cols = [col for col in data2013.columns]
# cols

In [4]:
results_dfs = wrangling(dfs)

~ Limpiando vías de transporte...
~ Limpiando NCMs...
~ Creando columna de precio...
~ Dropping outliers...
~ Dropping nulls...
> Done with: 2013
~~~~~~~~~~~~~~~~~~~
~ Limpiando vías de transporte...
~ Limpiando NCMs...
~ Creando columna de precio...
~ Dropping outliers...
~ Dropping nulls...
> Done with: 2014
~~~~~~~~~~~~~~~~~~~
~ Limpiando vías de transporte...
~ Limpiando NCMs...
~ Creando columna de precio...
~ Dropping outliers...
~ Dropping nulls...
> Done with: 2015
~~~~~~~~~~~~~~~~~~~
~ Limpiando vías de transporte...
~ Limpiando NCMs...
~ Creando columna de precio...
~ Dropping outliers...
~ Dropping nulls...
> Done with: 2016
~~~~~~~~~~~~~~~~~~~
~ Limpiando vías de transporte...
~ Limpiando NCMs...
~ Creando columna de precio...
~ Dropping outliers...
~ Dropping nulls...
> Done with: 2017
~~~~~~~~~~~~~~~~~~~
~ Limpiando vías de transporte...
~ Limpiando NCMs...
~ Creando columna de precio...
~ Dropping outliers...
~ Dropping nulls...
> Done with: 2018
~~~~~~~~~~~~~~~~~~~
~ Limpiando vías de transporte...
~ Limpiando NCMs...
~ Creando columna de precio...
~ Dropping outliers...
~ Dropping nulls...
> Done with: 2019
~~~~~~~~~~~~~~~~~~~
~ Limpiando vías de transporte...
~ Limpiando NCMs...
~ Creando columna de precio...
~ Dropping outliers...
~ Dropping nulls...
> Done with: 2020
~~~~~~~~~~~~~~~~~~~
~ Limpiando vías de transporte...
~ Limpiando NCMs...
~ Creando columna de precio...
~ Dropping outliers...
~ Dropping nulls...
> Done with: 2021
~~~~~~~~~~~~~~~~~~~
~ Limpiando vías de transporte...
~ Limpiando NCMs...
~ Creando columna de precio...
~ Dropping outliers...
~ Dropping nulls...
> Done with: 2022
~~~~~~~~~~~~~~~~~~~
~ Limpiando vías de transporte...
~ Limpiando NCMs...
~ Creando columna de precio...
~ Dropping outliers...
~ Dropping nulls...
> Done with: 2023
~~~~~~~~~~~~~~~~~~~

In [5]:
print(f"> Estadísticos del precio en el año per ton:\n___________________")

for df in results_dfs:
    print(
        f"- En el {df['Fecha'].iloc[5].year}:\n{df['U$S Unitario'].describe()}\n~~~~~~~~~~~~~~~~~~~")

> Estadísticos del precio en el año per ton:
___________________
- En el 2013:
count    159.000000
mean       0.582516
std        0.036750
min        0.480000
25%        0.570000
50%        0.590000
75%        0.605000
max        0.650000
Name: U$S Unitario, dtype: float64
~~~~~~~~~~~~~~~~~~~
- En el 2014:
count    173.000000
mean       0.513931
std        0.086707
min        0.310000
25%        0.500000
50%        0.540000
75%        0.580000
max        0.730000
Name: U$S Unitario, dtype: float64
~~~~~~~~~~~~~~~~~~~
- En el 2015:
count    220.000000
mean       0.445545
std        0.152867
min        0.020000
25%        0.280000
50%        0.540000
75%        0.560000
max        0.900000
Name: U$S Unitario, dtype: float64
~~~~~~~~~~~~~~~~~~~
- En el 2016:
count    232.000000
mean       0.397629
std        0.132515
min        0.180000
25%        0.267500
50%        0.480000
75%        0.480000
max        0.610000
Name: U$S Unitario, dtype: float64
~~~~~~~~~~~~~~~~~~~
- En el 2017:
count    214.000000
mean       0.437664
std        0.094696
min        0.260000
25%        0.340000
50%        0.460000
75%        0.480000
max        0.570000
Name: U$S Unitario, dtype: float64
~~~~~~~~~~~~~~~~~~~
- En el 2018:
count    215.000000
mean       0.417116
std        0.085364
min        0.280000
25%        0.340000
50%        0.420000
75%        0.460000
max        0.570000
Name: U$S Unitario, dtype: float64
~~~~~~~~~~~~~~~~~~~
- En el 2019:
count    167.000000
mean       0.400240
std        0.100965
min        0.250000
25%        0.300000
50%        0.420000
75%        0.500000
max        0.570000
Name: U$S Unitario, dtype: float64
~~~~~~~~~~~~~~~~~~~
- En el 2020:
count    184.000000
mean       0.390543
std        0.105218
min        0.240000
25%        0.290000
50%        0.420000
75%        0.480000
max        0.570000
Name: U$S Unitario, dtype: float64
~~~~~~~~~~~~~~~~~~~
- En el 2021:
count    176.000000
mean       0.507330
std        0.159084
min        0.260000
25%        0.380000
50%        0.500000
75%        0.625000
max        0.840000
Name: U$S Unitario, dtype: float64
~~~~~~~~~~~~~~~~~~~
- En el 2022:
count    219.000000
mean       0.770411
std        0.138210
min        0.400000
25%        0.670000
50%        0.800000
75%        0.880000
max        1.110000
Name: U$S Unitario, dtype: float64
~~~~~~~~~~~~~~~~~~~
- En el 2023:
count    8.000000
mean     0.767500
std      0.013887
min      0.760000
25%      0.760000
50%      0.760000
75%      0.767500
max      0.790000
Name: U$S Unitario, dtype: float64
~~~~~~~~~~~~~~~~~~~

In [6]:
annual_total_volume = annual_data(results_dfs)
annual_total_volume

- 2013 appended.
- 2014 appended.
- 2015 appended.
- 2016 appended.
- 2017 appended.
- 2018 appended.
- 2019 appended.
- 2020 appended.
- 2021 appended.
- 2022 appended.
- 2023 appended.
~~~~~~~~~~~~~~~~~~~
> Transition dictionary:
- NCM: ['283525', '283525', '283525', '283525', '283525', '283525', '283525', '283525', '283525', '283525', '283525']

- Año: [2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

- Volumen Total: [40758.53, 36934.05, 39910.77, 37367.34, 35732.67, 39563.16, 35937.04, 34092.11, 36071.19, 41844.51, 1594.25]

     Año     NCM  Volumen Total
0   2013  283525       40758.53
1   2014  283525       36934.05
2   2015  283525       39910.77
3   2016  283525       37367.34
4   2017  283525       35732.67
5   2018  283525       39563.16
6   2019  283525       35937.04
7   2020  283525       34092.11
8   2021  283525       36071.19
9   2022  283525       41844.51
10  2023  283525        1594.25

In [7]:
top_importadores = top_importadores(results_dfs)
top_importadores

- Done with: AGRICOLA CHOROMBO S.A (2013)
- Done with: ALIMENTOS AGROSUPER LTDA. (2013)
- Done with: AGR.Y GANAD.CHILLAN VIEJO S.A. (2013)
- Done with: AGRICOLA TARAPACA S.A. (2013)
- Done with: COEXPORT CHILE LTDA (2013)
- Done with: AGRICOLA EL MONTE S.A (2013)
- Done with: KUTULAS  RAZMILIC Y CIA. LTDA (2013)
- Done with: VETERQUIMICA S.A. (2013)
- Done with: ANASAC CHILE S.A. (2013)
- Done with: PROTEINAS DEL AGRO S.A. (2013)
- Done with: EXPORTADORA LOS FIORDOS LTDA. (2013)
- Done with: AVICOLA EL MONTE S.A (2013)
- Done with: SOC.PRODUCTORA Y DISTRIB.S.A. (2013)
- Done with: SOC.AGRICOLA LOS TILOS LTDA. (2013)
- Done with: CENTRO VETERIN.Y AGRICOLA LTDA (2013)
- Done with: COMERCIAL NATUFEED LIMITADA (2013)
- Done with: QUIMICA DEL PACIFICO LIMITADA (2013)
- Done with: NO DETERMINADO (2013)
- Done with: ALIMENTOS AGROSUPER LTDA. (2014)
- Done with: VETERQUIMICA S.A. (2014)
- Done with: COMERCIAL NATUFEED LIMITADA (2014)
- Done with: QUIMICA DEL PACIFICO LIMITADA (2014)
- Done with: KUTULAS  RAZMILIC Y CIA. LTDA (2014)
- Done with: AGRICOLA TARAPACA S.A. (2014)
- Done with: PROTEINAS DEL AGRO S.A. (2014)
- Done with: COEXPORT CHILE LTDA (2014)
- Done with: NO DETERMINADO (2014)
- Done with: CENTRO VETERIN.Y AGRICOLA LTDA (2014)
- Done with: AGRICOLA CHOROMBO S.A (2014)
- Done with: CRANDON CHILE LTDA. (2014)
- Done with: ANASAC CHILE S.A. (2014)
- Done with: AGRICOLA SUPER LIMITADA (2014)
- Done with: COMERCIAL NATUFEED LIMITADA (2015)
- Done with: AGRICOLA SUPER LIMITADA (2015)
- Done with: AGRICOLA CHOROMBO S.A (2015)
- Done with: VETERQUIMICA S.A. (2015)
- Done with: NO DETERMINADO (2015)
- Done with: QUIMICA DEL PACIFICO LIMITADA (2015)
- Done with: KUTULAS  RAZMILIC Y CIA. LTDA (2015)
- Done with: AGRICOLA TARAPACA S.A. (2015)
- Done with: EWOS CHILE ALIMENTOS LIMITADA (2015)
- Done with: PROTEINAS DEL AGRO S.A. (2015)
- Done with: IANSAGRO S A (2015)
- Done with: AGROFEED COMERCIALIZADORA SPA (2015)
- Done with: SOCIEDAD COMERCIAL ALIPECUARIA (2015)
- Done with: SOC.PRODUCTORA Y DISTRIB.S.A. (2015)
- Done with: CRANDON CHILE LTDA. (2015)
- Done with: COEXPORT CHILE LTDA (2015)
- Done with: AGRICOLA SUPER LIMITADA (2016)
- Done with: COMERCIAL NATUFEED LIMITADA (2016)
- Done with: PROTEINAS DEL AGRO S.A. (2016)
- Done with: QUIMICA DEL PACIFICO LIMITADA (2016)
- Done with: VETERQUIMICA S.A. (2016)
- Done with: AGRICOLA CHOROMBO S.A (2016)
- Done with: NO DETERMINADO (2016)
- Done with: AGROFEED COMERCIALIZADORA SPA (2016)
- Done with: COEXPORT CHILE LTDA (2016)
- Done with: KUTULAS  RAZMILIC Y CIA. LTDA (2016)
- Done with: COMERCIAL KIMBER S.A (2016)
- Done with: ANASAC CHILE S.A. (2016)
- Done with: EXPORTADORA LOS FIORDOS LTDA. (2016)
- Done with: CRANDON CHILE LTDA. (2016)
- Done with: ALINAT CHILE Y CIA LTDA (2016)
- Done with: DISTRIBUIDORA PORTLAND S A (2016)
- Done with: AGROFEED COMERCIALIZADORA SPA (2017)
- Done with: AGRICOLA SUPER LIMITADA (2017)
- Done with: COMERCIAL NATUFEED LIMITADA (2017)
- Done with: VETERQUIMICA S.A. (2017)
- Done with: NO DETERMINADO (2017)
- Done with: PROTEINAS DEL AGRO S.A. (2017)
- Done with: DISTRIBUIDORA PORTLAND S A (2017)
- Done with: EXPORTADORA LOS FIORDOS LTDA. (2017)
- Done with: AGRICOLA CHOROMBO S.A (2017)
- Done with: CHAMPION S.A. (2017)
- Done with: SOC.PRODUCTORA Y DISTRIB.S.A. (2017)
- Done with: QUIMICA DEL PACIFICO LIMITADA (2017)
- Done with: MANUCHAR CHILE S.A. (2017)
- Done with: COMERCIAL ASEGER LIMITADA (2017)
- Done with: ANASAC CHILE S.A. (2017)
- Done with: SUDAMERICA COMERCIAL S.A (2017)
- Done with: SERVICIOS DE MANTENCION LTDA. (2017)
- Done with: CHAMPION S.A. (2018)
- Done with: PROTEINAS DEL AGRO S.A. (2018)
- Done with: SUDAMERICA COMERCIAL S.A (2018)
- Done with: AGROFEED COMERCIALIZADORA SPA (2018)
- Done with: QUIMICA DEL PACIFICO LIMITADA (2018)
- Done with: EXPORTADORA LOS FIORDOS LTDA. (2018)
- Done with: AGRICOLA SUPER LIMITADA (2018)
- Done with: VETERQUIMICA S.A. (2018)
- Done with: AGRICOLA CHOROMBO S.A (2018)
- Done with: COMERCIAL NATUFEED LIMITADA (2018)
- Done with: ANASAC CHILE S.A. (2018)
- Done with: BRENNTAG CHILE COMERCIAL E IND (2018)
- Done with: MANUCHAR CHILE S.A. (2018)
- Done with: IANSAGRO S A (2018)
- Done with: NO DETERMINADO (2018)
- Done with: SERVICIOS DE MANTENCION LTDA. (2018)
- Done with: KUTULAS  RAZMILIC Y CIA. LTDA (2018)
- Done with: AGRICOLA SUPER LIMITADA (2019)
- Done with: AGROFEED COMERCIALIZADORA SPA (2019)
- Done with: PROTEINAS DEL AGRO S.A. (2019)
- Done with: ANASAC CHILE S.A. (2019)
- Done with: COMERCIAL NATUFEED LIMITADA (2019)
- Done with: QUIMICA DEL PACIFICO LIMITADA (2019)
- Done with: AGRICOLA CHOROMBO S.A (2019)
- Done with: VETERQUIMICA S.A. (2019)
- Done with: CHAMPION S.A. (2019)
- Done with: NO DETERMINADO (2019)
- Done with: SUDAMERICA COMERCIAL S.A (2019)
- Done with: IDAL S A (2019)
- Done with: QUIMICA MAVAR S.A. (2019)
- Done with: AGRICOLA SUPER LIMITADA (2020)
- Done with: ANASAC CHILE S.A. (2020)
- Done with: SUDAMERICA COMERCIAL S.A (2020)
- Done with: PROTEINAS DEL AGRO S.A. (2020)
- Done with: QUIMICA DEL PACIFICO LIMITADA (2020)
- Done with: AGRICOLA CHOROMBO S.A (2020)
- Done with: COMERCIAL NATUFEED LIMITADA (2020)
- Done with: AGROFEED COMERCIALIZADORA SPA (2020)
- Done with: VETERQUIMICA S.A. (2020)
- Done with: NO DETERMINADO (2020)
- Done with: NUTRIAL S.A. (2020)
- Done with: DSM NUTRITIONAL PRODUCTS CHILE (2020)
- Done with: CHAMPION S.A. (2020)
- Done with: ANASAC CHILE S.A. (2021)
- Done with: AGRICOLA SUPER LIMITADA (2021)
- Done with: COMERCIAL NATUFEED LIMITADA (2021)
- Done with: AGROFEED COMERCIALIZADORA SPA (2021)
- Done with: PROTEINAS DEL AGRO S.A. (2021)
- Done with: NO DETERMINADO (2021)
- Done with: QUIMICA DEL PACIFICO LIMITADA (2021)
- Done with: VETERQUIMICA S.A. (2021)
- Done with: AGRICOLA CHOROMBO S.A (2021)
- Done with: SUDAMERICA COMERCIAL S.A (2021)
- Done with: IDAL S A (2021)
- Done with: ASP CHILE S.A. (2021)
- Done with: VETERQUIMICA S.A. (2022)
- Done with: AGRICOLA SUPER LIMITADA (2022)
- Done with: ANASAC CHILE S.A. (2022)
- Done with: QUIMICA DEL PACIFICO LIMITADA (2022)
- Done with: NO DETERMINADO (2022)
- Done with: AGRICOLA CHOROMBO S.A (2022)
- Done with: SUDAMERICA COMERCIAL S.A (2022)
- Done with: COMERCIAL NATUFEED LIMITADA (2022)
- Done with: PROTEINAS DEL AGRO S.A. (2022)
- Done with: IDAL S A (2022)
- Done with: No disponible (2022)
- Done with: EXPORTADORA LOS FIORDOS LTDA. (2022)
- Done with: SOC.PRODUCTORA Y DISTRIB.S.A. (2022)
- Done with: AGRICOLA SUPER LIMITADA (2023)
- Done with: VETERQUIMICA S.A. (2023)
- Done with: EXPORTADORA LOS FIORDOS LTDA. (2023)
- Done with: QUIMICA DEL PACIFICO LIMITADA (2023)
~~~~~~~~~~~~~~~~~~~
> Current dataframe of the top 3 importers of each year:

,Año,Importador,Participacion,Precio Promedio,Volumen Total (TN)
1,2013,ALIMENTOS AGROSUPER LTDA.,73%,570.0,29618.39
7,2013,VETERQUIMICA S.A.,9%,600.0,3569.31
8,2013,ANASAC CHILE S.A.,6%,600.0,2254.75
0,2014,ALIMENTOS AGROSUPER LTDA.,66%,540.0,24422.85
3,2014,QUIMICA DEL PACIFICO LIMITADA,8%,600.0,3047.35
13,2014,AGRICOLA SUPER LIMITADA,6%,540.0,2277.00
1,2015,AGRICOLA SUPER LIMITADA,65%,540.0,25846.16
5,2015,QUIMICA DEL PACIFICO LIMITADA,8%,590.0,3228.40
11,2015,AGROFEED COMERCIALIZADORA SPA,5%,230.0,2176.00
0,2016,AGRICOLA SUPER LIMITADA,54%,490.0,20083.03
7,2016,AGROFEED COMERCIALIZADORA SPA,9%,250.0,3390.60
2,2016,PROTEINAS DEL AGRO S.A.,8%,240.0,3102.00
1,2017,AGRICOLA SUPER LIMITADA,60%,460.0,21618.00
0,2017,AGROFEED COMERCIALIZADORA SPA,9%,300.0,3289.00
11,2017,QUIMICA DEL PACIFICO LIMITADA,9%,560.0,3150.49
6,2018,AGRICOLA SUPER LIMITADA,57%,430.0,22392.75
3,2018,AGROFEED COMERCIALIZADORA SPA,11%,320.0,4310.00
2,2018,SUDAMERICA COMERCIAL S.A,6%,310.0,2470.35
0,2019,AGRICOLA SUPER LIMITADA,53%,420.0,18933.75
1,2019,AGROFEED COMERCIALIZADORA SPA,13%,290.0,4791.42
5,2019,QUIMICA DEL PACIFICO LIMITADA,9%,570.0,3144.13
0,2020,AGRICOLA SUPER LIMITADA,46%,420.0,15617.25
7,2020,AGROFEED COMERCIALIZADORA SPA,20%,280.0,6735.00
4,2020,QUIMICA DEL PACIFICO LIMITADA,9%,560.0,2991.50
1,2021,AGRICOLA SUPER LIMITADA,42%,570.0,15021.50
5,2021,NO DETERMINADO,14%,350.0,5173.75
6,2021,QUIMICA DEL PACIFICO LIMITADA,11%,600.0,4016.00
1,2022,AGRICOLA SUPER LIMITADA,46%,860.0,19156.91
10,2022,No disponible,16%,670.0,6518.00
3,2022,QUIMICA DEL PACIFICO LIMITADA,8%,820.0,3270.50
0,2023,AGRICOLA SUPER LIMITADA,79%,760.0,1262.25
2,2023,EXPORTADORA LOS FIORDOS LTDA.,12%,760.0,198.00
3,2023,QUIMICA DEL PACIFICO LIMITADA,5%,790.0,84.00

In [8]:
participacion_origenes = analisis_origenes(results_dfs)
participacion_origenes

- Done with: Perú (2013)
- Done with: China (2013)
- Done with: Bélgica (2013)
- Done with: Túnez (2013)
- Done with: Turquía (2013)
- Done with: Perú (2014)
- Done with: Túnez (2014)
- Done with: China (2014)
- Done with: Turquía (2014)
- Done with: China (2015)
- Done with: Perú (2015)
- Done with: Turquía (2015)
- Done with: Países Bajos (2015)
- Done with: Reino Unido (2015)
- Done with: Francia (2015)
- Done with: España (2015)
- Done with: España (2016)
- Done with: Perú (2016)
- Done with: China (2016)
- Done with: Túnez (2016)
- Done with: Turquía (2016)
- Done with: China (2017)
- Done with: Perú (2017)
- Done with: Turquía (2017)
- Done with: Estados Unidos (2017)
- Done with: Países Bajos (2017)
- Done with: Túnez (2017)
- Done with: España (2017)
- Done with: Estados Unidos (2018)
- Done with: China (2018)
- Done with: Perú (2018)
- Done with: España (2018)
- Done with: Francia (2018)
- Done with: Perú (2019)
- Done with: China (2019)
- Done with: Estados Unidos (2019)
- Done with: Perú (2020)
- Done with: China (2020)
- Done with: España (2020)
- Done with: China (2021)
- Done with: Perú (2021)
- Done with: España (2021)
- Done with: Turquía (2021)
- Done with: Túnez (2021)
- Done with: Estados Unidos (2021)
- Done with: Perú (2022)
- Done with: Estados Unidos (2022)
- Done with: China (2022)
- Done with: Túnez (2022)
- Done with: Perú (2023)
~~~~~~~~~~~~~~~~~~~
> Current dataframe of the origins of each year:

,NCM,Año,Pais,Volumen Total (TN),Participacion en Vol. Total,No. Importaciones
0,283525,2013,Perú,37450.23,92%,132
1,283525,2013,Bélgica,1872.00,5%,11
2,283525,2013,China,886.30,2%,13
3,283525,2013,Túnez,500.00,1%,2
4,283525,2013,Turquía,50.00,0%,1
0,283525,2014,Perú,30635.65,83%,120
1,283525,2014,China,4723.40,13%,49
2,283525,2014,Túnez,1500.00,4%,3
3,283525,2014,Turquía,75.00,0%,1
0,283525,2015,Perú,27115.31,68%,109
1,283525,2015,China,8887.67,22%,83
2,283525,2015,España,3422.41,9%,22
3,283525,2015,Países Bajos,288.00,1%,1
4,283525,2015,Turquía,100.00,0%,3
5,283525,2015,Reino Unido,72.38,0%,1
6,283525,2015,Francia,25.00,0%,1
0,283525,2016,Perú,23921.25,64%,124
1,283525,2016,China,12594.31,34%,101
2,283525,2016,Túnez,600.00,2%,3
3,283525,2016,España,226.78,1%,3
4,283525,2016,Turquía,25.00,0%,1
0,283525,2017,Perú,25238.12,71%,126
1,283525,2017,China,8215.00,23%,65
2,283525,2017,Túnez,1120.00,3%,10
3,283525,2017,Estados Unidos,914.05,3%,6
4,283525,2017,Turquía,199.00,1%,5
5,283525,2017,España,24.50,0%,1
6,283525,2017,Países Bajos,22.00,0%,1
0,283525,2018,Perú,25652.22,65%,117
1,283525,2018,China,12599.92,32%,81
2,283525,2018,Estados Unidos,1268.02,3%,15
3,283525,2018,Francia,22.00,0%,1
4,283525,2018,España,21.00,0%,1
0,283525,2019,Perú,24514.38,68%,89
1,283525,2019,China,11203.12,31%,74
2,283525,2019,Estados Unidos,219.54,1%,4
0,283525,2020,Perú,19408.65,57%,90
1,283525,2020,China,14421.70,42%,87
2,283525,2020,España,261.76,1%,7
0,283525,2021,Perú,18535.50,51%,106
1,283525,2021,China,14305.50,40%,59
2,283525,2021,Túnez,2000.00,6%,5
3,283525,2021,Estados Unidos,738.17,2%,1
4,283525,2021,España,481.02,1%,4
5,283525,2021,Turquía,11.00,0%,1
0,283525,2022,Perú,23125.60,55%,117
1,283525,2022,China,15228.75,36%,82
2,283525,2022,Túnez,2494.00,6%,7
3,283525,2022,Estados Unidos,996.16,2%,13
0,283525,2023,Perú,1594.25,100%,8

In [9]:
targets = ["ALIMENTOS AGROSUPER LTDA.", "AGRICOLA SUPER LIMITADA"]
analisis_precios = price_analysis(results_dfs, targets)
analisis_precios

- Price analysis finished for: ALIMENTOS AGROSUPER LTDA. (2013)
- Price analysis finished for: ALIMENTOS AGROSUPER LTDA. (2014)
- Price analysis finished for: AGRICOLA SUPER LIMITADA (2014)
- Price analysis finished for: AGRICOLA SUPER LIMITADA (2015)
- Price analysis finished for: AGRICOLA SUPER LIMITADA (2016)
- Price analysis finished for: AGRICOLA SUPER LIMITADA (2017)
- Price analysis finished for: AGRICOLA SUPER LIMITADA (2018)
- Price analysis finished for: AGRICOLA SUPER LIMITADA (2019)
- Price analysis finished for: AGRICOLA SUPER LIMITADA (2020)
- Price analysis finished for: AGRICOLA SUPER LIMITADA (2021)
- Price analysis finished for: AGRICOLA SUPER LIMITADA (2022)
- Price analysis finished for: AGRICOLA SUPER LIMITADA (2023)
~~~~~~~~~~~~~~~~~~~
> Price analysis for ALIMENTOS AGROSUPER LTDA., AGRICOLA SUPER LIMITADA in the last 10 years:

,Importador,Año,Minimo,Cuartiles,Maximo,Mediana,Promedio
0,ALIMENTOS AGROSUPER LTDA.,2013,520.0,Q1: 540.0 | Q3: 570.0,600.0,570.0,570.0
0,ALIMENTOS AGROSUPER LTDA.,2014,540.0,Q1: 540.0 | Q3: 540.0,540.0,540.0,540.0
1,AGRICOLA SUPER LIMITADA,2014,540.0,Q1: 540.0 | Q3: 540.0,540.0,540.0,540.0
0,AGRICOLA SUPER LIMITADA,2015,540.0,Q1: 540.0 | Q3: 560.0,570.0,560.0,550.0
0,AGRICOLA SUPER LIMITADA,2016,480.0,Q1: 480.0 | Q3: 480.0,480.0,480.0,480.0
0,AGRICOLA SUPER LIMITADA,2017,460.0,Q1: 460.0 | Q3: 460.0,460.0,460.0,460.0
0,AGRICOLA SUPER LIMITADA,2018,420.0,Q1: 420.0 | Q3: 460.0,460.0,420.0,430.0
0,AGRICOLA SUPER LIMITADA,2019,420.0,Q1: 420.0 | Q3: 420.0,420.0,420.0,420.0
0,AGRICOLA SUPER LIMITADA,2020,420.0,Q1: 420.0 | Q3: 430.0,440.0,420.0,420.0
0,AGRICOLA SUPER LIMITADA,2021,420.0,Q1: 450.0 | Q3: 690.0,840.0,520.0,570.0
0,AGRICOLA SUPER LIMITADA,2022,750.0,Q1: 850.0 | Q3: 890.0,930.0,880.0,860.0
0,AGRICOLA SUPER LIMITADA,2023,760.0,Q1: 760.0 | Q3: 760.0,760.0,760.0,760.0

In [10]:
# EXPORT TO PICKLE
CURRENT_WD = os.getcwd()
COUNTRY_WD = os.path.basename(CURRENT_WD).split('/')[-1]

# df_final.to_pickle(f'{COUNTRY_WD}.pkl')